import { createSeedCalendarContent } from '../localized';

export const content = createSeedCalendarContent({
  locale: 'de',
  title: 'Kalender für Samenbehandlung und Aussaattermine',
  description: 'Erstellen Sie einen datierten Vorbereitungsplan rückwärts vom Aussaattermin oder vorwärts vom Tag, an dem die Samen bereitliegen.',
  faq: [
    { question: 'Was berechnet dieser Kalender?', answer: 'Er legt Einweichen, warme und kalte Feuchtbehandlung sowie die Aussaat auf konkrete Tage, entweder rückwärts vom Zieltermin oder vorwärts vom Starttag.' },
    { question: 'Warum gibt es zwei Datumsmodi?', answer: 'Nutzen Sie den Aussaatmodus für einen festen Pflanztag und den Bereit-Modus, wenn die Vorbereitung heute beginnt und der spätere Aussaattermin gesucht wird.' },
    { question: 'Kann ich Dauer und Temperatur ändern?', answer: 'Ja. Wählen Sie ein Profil als Ausgangspunkt und passen Sie die Phasen an Saatgutpackung, Fachquelle und lokale Bedingungen an.' },
    { question: 'Garantiert der fertige Plan die Keimung?', answer: 'Nein. Der Plan organisiert Termine. Alter, Vitalität, Feuchtigkeit, Dormanz, Schimmel und Aussaatbedingungen beeinflussen das Ergebnis.' },
  ],
  howTo: [
    { name: 'Saatgutprofil wählen', text: 'Wählen Sie die passende Art, damit realistische Standardphasen geladen werden.' },
    { name: 'Datumsmodus wählen', text: 'Rechnen Sie von einem Zieltermin zurück oder vom Bereit-Tag nach vorn.' },
    { name: 'Phasen prüfen', text: 'Passen Sie Einweich-, Warm- und Kalttage sowie den kalten Temperaturbereich an.' },
    { name: 'Datierten Ablauf befolgen', text: 'Beginnen Sie am Startdatum, wechseln Sie ohne Lücke durch die Phasen und säen Sie am Zieltag.' },
  ],
  seoTitle: 'Das Vorbereitungsfenster planen',
  seoIntro: 'Samenruhe ist auch ein Zeitproblem. Wenn eine Art eine feuchte Kältephase braucht, kann ein zu später Beginn das Aussaatfenster verpassen. Eine unnötig lange Behandlung kostet Zeit und kann Schimmel oder vorzeitige Keimung begünstigen. Dieser Kalender macht aus einem Zieltermin eine klare Folge von Arbeitstagen.',
  seoModes: 'Wählen Sie den Zieltermin, um rückwärts zu rechnen, oder den Bereit-Modus, um vom Beginn der Vorbereitung vorwärts zu rechnen. Jede Phase erhält eigene Daten; dadurch endet das Einweichen direkt vor der nächsten Behandlung und die letzte Behandlung endet am Tag vor der Aussaat. Der Plan eignet sich zum Beschriften eines Behälters und für Erinnerungen.',
  seoPhaseTitle: 'Die Phasen richtig lesen',
  seoPhaseItems: ['<strong>Einweichen:</strong> Befeuchten Sie das Saatgut nur so lange, wie das Profil oder Ihre Fachquelle vorgibt.', '<strong>Warm:</strong> Halten Sie feuchtes Saatgut im angezeigten warmen Bereich, wenn diese Phase erforderlich ist.', '<strong>Kalt:</strong> Halten Sie das Saatgut feucht und kühl und prüfen Sie es regelmäßig auf Schimmel oder Wurzeln.', '<strong>Aussaat:</strong> Setzen Sie das vorbereitete Saatgut am Zieltag in ein passendes, gut drainiertes Substrat.'],
  seoEvidenceTitle: 'Profile als Ausgangspunkt verwenden',
  seoEvidence: 'Die Profile sind keine universellen Vorschriften. Sorte, Herkunft, Saatgutalter und die Angaben auf der Packung können die Dormanz verändern. Wenn ein seriöser Anbieter eine andere Dauer nennt, bearbeiten Sie das Profil und dokumentieren Sie die verwendete Quelle, statt widersprüchliche Angaben blind zu mitteln.',
  seoTipTitle: 'Ein Kalender ist kein Keimtest',
  seoTip: 'Notieren Sie Saatgutpartie, Feuchtmedium, Temperatur und Behandlungsdaten. Wenn während der Kältephase Wurzeln erscheinen, säen Sie vorsichtig aus. Bleibt das Saatgut dormant, verlängern Sie die Behandlung nicht automatisch.',
  seoChecksTitle: 'Vor dem Start prüfen',
  seoChecks: ['Prüfen Sie, ob der Aussaattermin zu Licht, Frost und Standort passt.', 'Beschriften Sie den Behälter mit Art, Start, Ende und Temperaturbereich.', 'Verwenden Sie ein feuchtes, luftiges Medium und kontrollieren Sie es regelmäßig.', 'Bewahren Sie den Plan bei der Saatgutpackung auf, damit der Versuch nachvollziehbar bleibt.'],
  seoLimitsTitle: 'Was das Ergebnis nicht sagen kann',
  seoLimits: 'Das Tool bestimmt keine Dormanz aus einem Foto, prüft keine Keimfähigkeit und ersetzt keine artspezifische Anleitung. Es sagt auch nicht voraus, wie Wetter oder Standort wirken, und verspricht keine Keimung. Behandeln Sie die Ausgabe als organisierte Datumsrechnung und prüfen Sie die Biologie mit einer passenden Quelle.',
  ui: {
    labelProfile: 'Saatgutprofil', labelMode: 'Planmodus', labelModeSowing: 'Ich möchte säen am', labelModeReady: 'Saatgut ist heute bereit', labelSowingDate: 'Zieltermin der Aussaat', labelReadyDate: 'Bereitdatum', labelSoakDays: 'Einweichtage', labelWarmDays: 'Warme Tage', labelColdDays: 'Kalte Tage', labelColdRange: 'Kalter Temperaturbereich', labelUnits: 'Temperatureinheiten', labelMetric: 'Metrisch °C', labelImperial: 'Imperial °F', labelFrom: 'Mindesttemperatur', labelTo: 'Höchsttemperatur', labelGenerate: 'Kalender aktualisieren', labelReset: 'Profil zurücksetzen', labelAddCalendar: 'Zum Kalender hinzufügen', labelShare: 'Link kopieren', labelCopied: 'Link kopiert', labelPrint: 'Kompaktes Etikett drucken', labelTechnique: 'Methode', labelTodayStatus: 'Heute aktiv', labelDayOf: 'Tag von', labelGantt: 'Vorbereitungszeitraum', labelTimeline: 'Vorbereitungszeitraum', labelNextAction: 'Aktuelle Phase', labelCalendarStarts: 'Kalenderstart', labelSowingDay: 'Aussaat', labelDuration: 'Vorbereitung', labelDays: 'Tage', labelTemperature: 'Temperatur', labelReady: 'Heute aussäen', labelUpcoming: 'Bevorstehend', labelActive: 'In Bearbeitung', labelComplete: 'Plan abgeschlossen', labelEditHint: 'Passen Sie die Vorschläge anhand von Packungs- oder Fachangaben an. Die letzten Einstellungen werden auf diesem Gerät gespeichert.', labelWarm: 'Warme Stratifikation', labelCold: 'Kalte Stratifikation', labelSoak: 'Samen einweichen', labelSow: 'Samen aussäen', noteApple: 'Feuchte Kältephase nach kurzem Einweichen', noteLavender: 'Kurze Kältephase vor der Frühjahrsaussaat', noteMilkweed: 'Warme Phase gefolgt von einer kalten Phase', noteRose: 'Lange Kältephase nach dem Einweichen', profileApple: 'Apfel · Malus domestica', profileLavender: 'Lavendel · Lavandula angustifolia', profileMilkweed: 'Seidenpflanze · Asclepias syriaca', profileRose: 'Rose · Rosa spp.', profileStrawberry: 'Erdbeere · Fragaria × ananassa', profilePeach: 'Pfirsich · Prunus persica', profileCherry: 'Süßkirsche · Prunus avium', profilePear: 'Birne · Pyrus communis', profilePoppy: 'Mohn · Papaver spp.', profileSunflower: 'Sonnenblume · Helianthus annuus', profileTomato: 'Tomate · Solanum lycopersicum', profileBasil: 'Basilikum · Ocimum basilicum', instructionSoak: 'Halten Sie die Samen vor der nächsten Phase hydratisiert.', instructionWarm: 'Bewahren Sie die feuchten Samen an einem warmen Ort auf.', instructionCold: 'Halten Sie die feuchten Samen kühl und kontrollieren Sie sie regelmäßig.', instructionSow: 'Säen Sie in das vorbereitete Anzuchtsubstrat.', emptyState: 'Legen Sie Ihre Daten fest, um einen Vorbereitungsplan zu erstellen.', warningDate: 'Wählen Sie ein gültiges Aussaatdatum.', warningTemperature: 'Prüfen Sie Dauer und Temperatur, bevor Sie den Kalender aktualisieren.',
  },
});
