import { createSeedCalendarContent } from '../localized';

export const content = createSeedCalendarContent({
  locale: 'es',
  title: 'Calendario de estratificación de semillas y fechas de siembra',
  description: 'Crea un plan de preparación con fechas, contando hacia atrás desde la siembra o hacia delante desde el día en que tienes las semillas listas.',
  faq: [
    { question: '¿Qué calcula este calendario?', answer: 'Coloca el remojo, las fases húmedas templada y fría y la siembra en días concretos, contando hacia atrás desde la fecha objetivo o hacia delante desde el inicio.' },
    { question: '¿Por qué hay dos modos de fecha?', answer: 'Usa el modo de siembra cuando el día de plantar es fijo, o el modo semillas listas cuando la preparación comienza hoy y necesitas conocer la fecha futura de siembra.' },
    { question: '¿Puedo cambiar la duración y la temperatura?', answer: 'Sí. Elige un perfil como punto de partida y ajusta las fases a la etiqueta del paquete, una fuente especializada y tus condiciones locales.' },
    { question: '¿El plan garantiza la germinación?', answer: 'No. Organiza fechas, pero la edad, viabilidad, humedad, dormición, moho y condiciones de siembra también afectan al resultado.' },
  ],
  howTo: [
    { name: 'Elegir un perfil', text: 'Selecciona la especie más cercana para cargar fases y duraciones iniciales realistas.' },
    { name: 'Elegir el modo de fecha', text: 'Cuenta hacia atrás desde el día de siembra o hacia delante desde el día en que las semillas están listas.' },
    { name: 'Revisar las fases', text: 'Ajusta los días de remojo, calor y frío y el intervalo de temperatura fría.' },
    { name: 'Seguir la secuencia', text: 'Empieza en la fecha inicial, pasa por cada fase sin saltos y siembra el día indicado.' },
  ],
  seoTitle: 'Planifica la ventana de preparación',
  seoIntro: 'La dormición de una semilla también es un problema de calendario. Si una especie necesita un periodo frío y húmedo, empezar tarde puede hacerte perder la ventana de siembra. Alargar una preparación sin motivo consume tiempo y puede favorecer el moho o una germinación prematura. Esta herramienta convierte la fecha objetivo en una secuencia que puedes seguir.',
  seoModes: 'Elige una fecha objetivo para contar hacia atrás, o usa el modo de semillas listas para contar hacia delante desde el comienzo de la preparación. Cada fase tiene fechas propias: el remojo enlaza con el tratamiento siguiente y el último tratamiento termina el día anterior a la siembra. Puedes usar el resultado para etiquetar un recipiente o crear recordatorios.',
  seoPhaseTitle: 'Cómo leer cada fase',
  seoPhaseItems: ['<strong>Remojo:</strong> hidrata las semillas durante los días indicados y no prolongues el tiempo sin una razón específica.', '<strong>Templada:</strong> conserva la semilla húmeda dentro del intervalo cálido cuando el perfil lo requiere.', '<strong>Fría:</strong> mantenla húmeda y refrigerada y revisa con frecuencia si hay moho o raíces tempranas.', '<strong>Siembra:</strong> pasa la semilla preparada a un sustrato adecuado el día objetivo.'],
  seoEvidenceTitle: 'Usa los perfiles como punto de partida',
  seoEvidence: 'Los perfiles no son recetas universales. La variedad, el origen, la edad de la semilla y las indicaciones del envase pueden cambiar la dormición. Si un proveedor fiable recomienda otra duración, edita el perfil y registra la fuente utilizada en lugar de promediar indicaciones contradictorias.',
  seoTipTitle: 'Un calendario no es una prueba de germinación',
  seoTip: 'Anota el lote, el medio húmedo, la temperatura y las fechas. Si aparecen raíces durante el frío, siembra con cuidado. Si la semilla sigue dormida, no alargues el tratamiento automáticamente: comprueba primero la guía de la especie.',
  seoChecksTitle: 'Comprobaciones antes de empezar',
  seoChecks: ['Confirma que la fecha de siembra encaja con la luz, las heladas y el lugar.', 'Etiqueta el recipiente con especie, inicio, final e intervalo térmico.', 'Usa un medio húmedo pero aireado y revísalo con regularidad.', 'Guarda el plan junto al paquete para poder rastrear el tratamiento realizado.'],
  seoLimitsTitle: 'Lo que el resultado no puede decir',
  seoLimits: 'La herramienta no identifica la dormición a partir de una foto, no comprueba la viabilidad ni sustituye las instrucciones específicas de una especie. Tampoco predice el tiempo local ni garantiza que germinen todas las semillas. Interpreta el resultado como un cálculo organizado de fechas y verifica la biología con una fuente adecuada.',
  ui: {
    labelProfile: 'Perfil de semilla', labelMode: 'Modo del plan', labelModeSowing: 'Quiero sembrar el', labelModeReady: 'Tengo las semillas listas hoy', labelSowingDate: 'Fecha objetivo de siembra', labelReadyDate: 'Fecha de inicio', labelSoakDays: 'Días de remojo', labelWarmDays: 'Días templados', labelColdDays: 'Días fríos', labelColdRange: 'Intervalo de frío', labelUnits: 'Unidades de temperatura', labelMetric: 'Métrico °C', labelImperial: 'Imperial °F', labelFrom: 'Temperatura mínima', labelTo: 'Temperatura máxima', labelGenerate: 'Actualizar calendario', labelReset: 'Restablecer perfil', labelAddCalendar: 'Añadir a mi calendario', labelShare: 'Copiar enlace', labelCopied: 'Enlace copiado', labelPrint: 'Imprimir etiqueta compacta', labelTechnique: 'Técnica', labelTodayStatus: 'Estado de hoy', labelDayOf: 'día de', labelGantt: 'Línea de preparación', labelTimeline: 'Línea de preparación', labelNextAction: 'Fase actual', labelCalendarStarts: 'inicio del calendario', labelSowingDay: 'día de siembra', labelDuration: 'Preparación', labelDays: 'días', labelTemperature: 'Temperatura', labelReady: 'Sembrar hoy', labelUpcoming: 'Próxima', labelActive: 'En curso', labelComplete: 'Plan completado', labelEditHint: 'Ajusta las sugerencias con la información del paquete o de una fuente especializada. El último ajuste se guarda en este dispositivo.', labelWarm: 'Estratificación templada', labelCold: 'Estratificación fría', labelSoak: 'Remojar semillas', labelSow: 'Sembrar semillas', noteApple: 'Periodo frío húmedo tras un remojo corto', noteLavender: 'Periodo frío breve antes de la siembra primaveral', noteMilkweed: 'Fase templada seguida de una fase fría', noteRose: 'Periodo frío largo tras el remojo', profileApple: 'Manzana · Malus domestica', profileLavender: 'Lavanda · Lavandula angustifolia', profileMilkweed: 'Algodoncillo · Asclepias syriaca', profileRose: 'Rosa · Rosa spp.', profileStrawberry: 'Fresa · Fragaria × ananassa', profilePeach: 'Melocotón · Prunus persica', profileCherry: 'Cerezo dulce · Prunus avium', profilePear: 'Peral · Pyrus communis', profilePoppy: 'Amapola · Papaver spp.', profileSunflower: 'Girasol · Helianthus annuus', profileTomato: 'Tomate · Solanum lycopersicum', profileBasil: 'Albahaca · Ocimum basilicum', instructionSoak: 'Mantén las semillas hidratadas antes de la siguiente fase.', instructionWarm: 'Conserva las semillas húmedas en un lugar templado.', instructionCold: 'Mantén las semillas húmedas y frías y revísalas con frecuencia.', instructionSow: 'Siembra en el sustrato preparado.', emptyState: 'Configura las fechas para crear una línea de preparación.', warningDate: 'Elige una fecha de siembra válida.', warningTemperature: 'Revisa los días y la temperatura antes de actualizar el calendario.',
  },
});
