import { createSeedCalendarContent } from '../localized';

export const content = createSeedCalendarContent({
  locale: 'fr',
  title: 'Calendrier de stratification des graines et de semis',
  description: 'Créez un plan daté de préparation en remontant depuis le semis ou en avançant depuis le jour où vos graines sont prêtes.',
  faq: [
    { question: 'Que calcule ce calendrier ?', answer: 'Il place le trempage, les phases humides chaude et froide, puis le semis à des dates précises, en remontant depuis la date cible ou en avançant depuis le début.' },
    { question: 'Pourquoi proposer deux modes de date ?', answer: 'Utilisez le mode date de semis si le jour de plantation est fixé, ou le mode graines prêtes si la préparation commence aujour0027ui et que vous cherchez le jour futur du semis.' },
    { question: 'Puis-je modifier les durées et la température ?', answer: 'Oui. Choisissez un profil de départ, puis adaptez les phases au sachet, à une source spécialisée et à vos conditions locales.' },
    { question: 'Le plan garantit-il la germination ?', answer: 'Non. Il organise les dates, mais 0027ge, la viabilité, 0027umidité, la dormance, les moisissures et les conditions de semis influencent aussi le résultat.' },
  ],
  howTo: [
    { name: 'Choisir un profil', text: 'Sélectionnez 0027spèce la plus proche pour charger des phases initiales cohérentes.' },
    { name: 'Choisir le mode de date', text: 'Remontez depuis le jour de semis ou avancez depuis le jour où les graines sont prêtes.' },
    { name: 'Vérifier les phases', text: 'Ajustez les jours de trempage, de chaleur et de froid ainsi que la plage froide.' },
    { name: 'Suivre la séquence', text: 'Commencez à la date initiale, enchaînez chaque phase et semez le jour indiqué.' },
  ],
  seoTitle: 'Planifier la période de préparation',
  seoIntro: 'La dormance des graines est aussi un problème de calendrier. Une espèce qui exige une période froide et humide peut manquer sa fenêtre de semis si la préparation commence trop tard. Une durée excessive fait perdre du temps et peut favoriser les moisissures ou une germination précoce. Ce calendrier transforme la date cible en étapes datées et faciles à suivre.',
  seoModes: 'Choisissez une date de semis cible pour compter à rebours, ou utilisez le mode graines prêtes pour compter depuis le début de la préparation. Chaque phase possède ses propres dates: le trempage rejoint le traitement suivant et le dernier traitement se termine la veille du semis. Le résultat peut servir à étiqueter un récipient ou à créer des rappels.',
  seoPhaseTitle: 'Lire les différentes phases',
  seoPhaseItems: ['<strong>Trempage :</strong> hydratez les graines pendant la durée indiquée, sans prolonger le traitement sans raison précise.', '<strong>Chaleur :</strong> gardez les graines humides dans la plage chaude lorsque le profil le demande.', '<strong>Froid :</strong> conservez-les humides et au frais, en vérifiant régulièrement les moisissures ou les racines.', '<strong>Semis :</strong> placez les graines préparées dans un substrat adapté à la date cible.'],
  seoEvidenceTitle: 'Utiliser les profils comme points de départ',
  seoEvidence: 'Les profils ne sont pas des prescriptions universelles. La variété, 0027rigine, 0027ge des graines et les indications du sachet peuvent modifier la dormance. Si un fournisseur fiable recommande une autre durée, modifiez le profil et notez la source utilisée au lieu de moyenner des conseils contradictoires.',
  seoTipTitle: 'Un calendrier 0027st pas un test de germination',
  seoTip: 'Notez le lot, le support humide, la température et les dates. Si des racines apparaissent pendant le froid, semez avec précaution. Si les graines restent dormantes, ne prolongez pas automatiquement le traitement: vérifiez 0027bord les conseils propres à 0027spèce.',
  seoChecksTitle: 'Vérifications avant de commencer',
  seoChecks: ['Vérifiez que la date de semis convient à la lumière, au gel et au lieu.', 'Étiquetez le récipient avec 0027spèce, le début, la fin et la plage thermique.', 'Utilisez un support humide mais aéré et contrôlez-le régulièrement.', 'Conservez le plan avec le sachet pour pouvoir retracer le traitement.'],
  seoLimitsTitle: 'Ce que le résultat ne peut pas dire',
  seoLimits: '0027util ne détermine pas la dormance à partir 0027ne photo, ne teste pas la viabilité et ne remplace pas les instructions propres à une espèce. Il ne prédit pas non plus la météo locale et ne garantit pas la germination. Considérez-le comme un calcul de dates et vérifiez la biologie avec une source adaptée.',
  ui: {
    labelProfile: 'Profil de graines', labelMode: 'Mode du plan', labelModeSowing: 'Je veux semer le', labelModeReady: 'Les graines sont prêtes aujour0027ui', labelSowingDate: 'Date cible du semis', labelReadyDate: 'Date de préparation', labelSoakDays: 'Jours de trempage', labelWarmDays: 'Jours chauds', labelColdDays: 'Jours froids', labelColdRange: 'Plage de froid', labelUnits: 'Unités de température', labelMetric: 'Métrique °C', labelImperial: 'Impériale °F', labelFrom: 'Température minimale', labelTo: 'Température maximale', labelGenerate: 'Actualiser le calendrier', labelReset: 'Réinitialiser le profil', labelAddCalendar: 'Ajouter à mon calendrier', labelShare: 'Copier le lien', labelCopied: 'Lien copié', labelPrint: 'Imprimer une étiquette compacte', labelTechnique: 'Technique', labelTodayStatus: 'État du jour', labelDayOf: 'jour sur', labelGantt: 'Chronologie de préparation', labelTimeline: 'Chronologie de préparation', labelNextAction: 'Phase actuelle', labelCalendarStarts: 'début du calendrier', labelSowingDay: 'jour du semis', labelDuration: 'Préparation', labelDays: 'jours', labelTemperature: 'Température', labelReady: 'Semer aujour0027ui', labelUpcoming: 'À venir', labelActive: 'En cours', labelComplete: 'Plan terminé', labelEditHint: 'Adaptez les suggestions avec les indications du sachet ou 0027ne source spécialisée. Le dernier réglage est conservé sur cet appareil.', labelWarm: 'Stratification chaude', labelCold: 'Stratification froide', labelSoak: 'Faire tremper les graines', labelSow: 'Semer les graines', noteApple: 'Période froide humide après un bref trempage', noteLavender: 'Courte période froide avant le semis de printemps', noteMilkweed: 'Phase chaude suivie 0027ne phase froide', noteRose: 'Longue période froide après trempage', profileApple: 'Pomme · Malus domestica', profileLavender: 'Lavande · Lavandula angustifolia', profileMilkweed: 'Asclépiade · Asclepias syriaca', profileRose: 'Rose · Rosa spp.', profileStrawberry: 'Fraise · Fragaria × ananassa', profilePeach: 'Pêcher · Prunus persica', profileCherry: 'Cerisier doux · Prunus avium', profilePear: 'Poirier · Pyrus communis', profilePoppy: 'Coquelicot · Papaver spp.', profileSunflower: 'Tournesol · Helianthus annuus', profileTomato: 'Tomate · Solanum lycopersicum', profileBasil: 'Basilic · Ocimum basilicum', instructionSoak: 'Gardez les graines hydratées avant la phase suivante.', instructionWarm: 'Conservez les graines humides dans un endroit chaud.', instructionCold: 'Gardez les graines humides et froides et vérifiez-les régulièrement.', instructionSow: 'Semez dans le substrat préparé.', emptyState: 'Définissez vos dates pour créer une chronologie de préparation.', warningDate: 'Choisissez une date de semis valide.', warningTemperature: 'Vérifiez les durées et la température avant 0027ctualiser le calendrier.',
  },
});
