import { createSeedCalendarContent } from '../localized';

export const content = createSeedCalendarContent({
  locale: 'it',
  title: 'Calendario di stratificazione dei semi e delle semine',
  description: 'Crea un piano di preparazione con date precise, contando a ritroso dalla semina o in avanti dal giorno in cui i semi sono pronti.',
  faq: [
    { question: 'Che cosa calcola questo calendario?', answer: 'Colloca ammollo, fasi umide calda e fredda e semina in date precise, contando a ritroso dalla data obiettivo o in avanti dal0027nizio.' },
    { question: 'Perché ci sono due modalità di data?', answer: 'Usa la modalità data di semina quando il giorno è fisso, oppure la modalità semi pronti quando la preparazione inizia oggi e vuoi conoscere il giorno futuro della semina.' },
    { question: 'Posso modificare durata e temperatura?', answer: 'Sì. Scegli un profilo iniziale e adatta le fasi alle indicazioni della confezione, a una fonte specializzata e alle condizioni locali.' },
    { question: 'Il piano garantisce la germinazione?', answer: 'No. Organizza le date, ma età, vitalità, umidità, dormienza, muffe e condizioni di semina influenzano il risultato.' },
  ],
  howTo: [
    { name: 'Scegli un profilo', text: 'Seleziona la specie più vicina per caricare fasi iniziali plausibili.' },
    { name: 'Scegli la modalità', text: 'Conta a ritroso dal giorno di semina oppure in avanti dal giorno in cui i semi sono pronti.' },
    { name: 'Controlla le fasi', text: 'Modifica i giorni di ammollo, caldi e freddi e 0027ntervallo di temperatura fredda.' },
    { name: 'Segui la sequenza', text: 'Inizia dalla data iniziale, completa ogni fase e semina nel giorno indicato.' },
  ],
  seoTitle: 'Pianifica il periodo di preparazione',
  seoIntro: 'La dormienza dei semi è anche un problema di calendario. Se una specie richiede un periodo freddo e umido, iniziare tardi può far perdere la finestra di semina. Un trattamento inutilmente lungo fa perdere tempo e può favorire muffe o germinazione anticipata. Questo calendario trasforma la data obiettivo in una sequenza di attività datate.',
  seoModes: 'Scegli una data obiettivo per contare a ritroso, oppure usa la modalità semi pronti per contare in avanti dal0027nizio della preparazione. Ogni fase ha date proprie: 0027mmollo conduce al trattamento successivo e 0027ltimo trattamento finisce il giorno prima della semina. Il risultato è utile per etichettare un contenitore e impostare promemoria.',
  seoPhaseTitle: 'Come leggere le fasi',
  seoPhaseItems: ['<strong>Ammollo:</strong> idrata i semi per i giorni indicati e non prolungare il trattamento senza una ragione precisa.', '<strong>Caldo:</strong> mantieni i semi umidi nel0027ntervallo caldo quando il profilo lo richiede.', '<strong>Freddo:</strong> conservali umidi e al fresco, controllando spesso muffe o radici precoci.', '<strong>Semina:</strong> trasferisci i semi preparati in un substrato adatto nella data obiettivo.'],
  seoEvidenceTitle: 'Usa i profili come punto di partenza',
  seoEvidence: 'I profili non sono prescrizioni universali. Varietà, provenienza, età del seme e indicazioni sulla confezione possono cambiare la dormienza. Se un fornitore affidabile indica una durata diversa, modifica il profilo e registra la fonte usata invece di fare una media tra consigli in conflitto.',
  seoTipTitle: 'Un calendario non è un test di germinazione',
  seoTip: 'Annota lotto, materiale umido, temperatura e date. Se compaiono radici durante il freddo, semina con attenzione. Se i semi restano dormienti, non prolungare automaticamente il trattamento: controlla prima le indicazioni per la specie.',
  seoChecksTitle: 'Controlli prima di iniziare',
  seoChecks: ['Verifica che la data di semina sia compatibile con luce, gelate e luogo.', 'Etichetta il contenitore con specie, inizio, fine e intervallo termico.', 'Usa un materiale umido ma arieggiato e controllalo regolarmente.', 'Conserva il piano con la confezione per poter ricostruire il trattamento.'],
  seoLimitsTitle: 'Che cosa il risultato non può dire',
  seoLimits: 'Lo strumento non identifica la dormienza da una foto, non verifica la vitalità e non sostituisce le istruzioni specifiche di una specie. Non predice il clima locale e non garantisce la germinazione. Considera il risultato un calcolo organizzato di date e verifica la biologia con una fonte adeguata.',
  ui: {
    labelProfile: 'Profilo del seme', labelMode: 'Modalità del piano', labelModeSowing: 'Voglio seminare il', labelModeReady: 'I semi sono pronti oggi', labelSowingDate: 'Data obiettivo di semina', labelReadyDate: 'Data di preparazione', labelSoakDays: 'Giorni di ammollo', labelWarmDays: 'Giorni caldi', labelColdDays: 'Giorni freddi', labelColdRange: 'Intervallo freddo', labelUnits: 'Unità di temperatura', labelMetric: 'Metrico °C', labelImperial: 'Imperiale °F', labelFrom: 'Temperatura minima', labelTo: 'Temperatura massima', labelGenerate: 'Aggiorna calendario', labelReset: 'Reimposta profilo', labelAddCalendar: 'Aggiungi al calendario', labelShare: 'Copia link', labelCopied: 'Link copiato', labelPrint: 'Stampa etichetta compatta', labelTechnique: 'Tecnica', labelTodayStatus: 'Stato di oggi', labelDayOf: 'giorno di', labelGantt: 'Cronologia di preparazione', labelTimeline: 'Cronologia di preparazione', labelNextAction: 'Fase attuale', labelCalendarStarts: 'inizio del calendario', labelSowingDay: 'giorno della semina', labelDuration: 'Preparazione', labelDays: 'giorni', labelTemperature: 'Temperatura', labelReady: 'Semina oggi', labelUpcoming: 'In arrivo', labelActive: 'In corso', labelComplete: 'Piano completato', labelEditHint: 'Adatta i suggerimenti usando la confezione o una fonte specializzata. 0027ltima impostazione viene salvata su questo dispositivo.', labelWarm: 'Stratificazione calda', labelCold: 'Stratificazione fredda', labelSoak: 'Metti a bagno i semi', labelSow: 'Semina i semi', noteApple: 'Periodo freddo umido dopo un breve ammollo', noteLavender: 'Breve periodo freddo prima della semina primaverile', noteMilkweed: 'Fase calda seguita da una fase fredda', noteRose: 'Lungo periodo freddo dopo 0027mmollo', profileApple: 'Mela · Malus domestica', profileLavender: 'Lavanda · Lavandula angustifolia', profileMilkweed: 'Asclepiade · Asclepias syriaca', profileRose: 'Rosa · Rosa spp.', profileStrawberry: 'Fragola · Fragaria × ananassa', profilePeach: 'Pesco · Prunus persica', profileCherry: 'Ciliegio dolce · Prunus avium', profilePear: 'Pero · Pyrus communis', profilePoppy: 'Papavero · Papaver spp.', profileSunflower: 'Girasole · Helianthus annuus', profileTomato: 'Pomodoro · Solanum lycopersicum', profileBasil: 'Basilico · Ocimum basilicum', instructionSoak: 'Mantieni i semi idratati prima della fase successiva.', instructionWarm: 'Conserva i semi umidi in un luogo caldo.', instructionCold: 'Mantieni i semi umidi e freddi e controllali regolarmente.', instructionSow: 'Semina nel substrato preparato.', emptyState: 'Imposta le date per creare una cronologia di preparazione.', warningDate: 'Scegli una data di semina valida.', warningTemperature: 'Controlla durata e temperatura prima di aggiornare il calendario.',
  },
});
